export const API_URL = `https://uptapapi.uptap.com/h5Game/?type=GameList&platform=uptapgame0120&token=dXB0YXBnYW1l572R56uZ55So`; //游戏源
export const GAME_PATH = `https://uptapapi.uptap.com/h5Game/?type=Game&platform=uptapin&appid=`; //渠道游戏路径
export const IMAGE_PATH = `https://cdn.iwantalipstick.com/gameicon2/`;
export const IMAGE_FORMAT = `jpg`;

export const SITE_META = {
  name: `Supereasy Game`,
  url: `https://www.supereasygame.com/`,
  domain: `supereasygame.com`,
};

// export const GA_ID = `UA-183890722-4`; //Google Analytics ID
export const GA_ID = `G-9MEPVR3114`; //Google Analytics ID
export const ADS_ID = `ca-pub-9209477879340784`; //Google Adsense ID

export const ADS_SLOT_ID = {
  home: `4124206286`,
  category: `4124206286`,
  detail: `4124206286`,
};

export const SELECTED_GAMES = [
  "4096",
  "8BallKing",
  "AceMan",
  "AirHockey3D",
  "AmazingRoad",
  "AnipopLink",
  "ArchersKing",
  "ArcheryMaster",
  "BallIsComing",
  "BatterKing",
  "BigSword",
  "BlockGun3D",
  "BlockPuzzle",
  "BoardTheTrain",
  "BubbleBlast",
  "BulletMaster3D",
  "BumbleShooter",
  "Chess3D",
  "CollectColorfulBalls",
  "ColorBall3D",
  "CrashTower3D",
  "CrazyBomb",
  "CrazyHammer",
  "CrazyKnife",
  "CrazyMoto",
  "CrazyPortal",
  "CrazyRace",
  "CrazyTrain3D",
  "DartsKing3D",
  "DeathJump",
  "DeathRun",
  "DefenseTower",
  "DragonCrush",
  "DressQueen",
  "FairyTalesPuzzle",
  "FeverRacing",
  "FillTheGlass",
  "FireTheGun",
  "FisherMan",
  "FlyPass",
  "GoldenGlove",
  "GunShooter",
  "HappyBilliards",
  "HelpTheZombie",
  "HiTaxi",
  "HillRacing",
  "HungryAnimals",
  "HungryMonster",
  "HungyBunny",
  "IdleRestaurantTycoon",
  "ImEmpire",
  "JumpingMonkey",
  "KillAllZombies",
  "KimbapRun",
  "Knife",
  "KnockBalls",
  "LetMeIn",
  "MagicDonuts",
  "MagicJigsaw",
  "MagicNumber",
  "MahjongConnect",
  "MahjongLink",
  "MahjongLink3D",
  "MergeAndDefense",
  "MergeGuns3D",
  "MergeKill",
  "MergeMagicJewellery",
  "Mining",
  "MiningMaster",
  "MrBullet",
  "MyBabyCare",
  "MyBowling3D",
  "MyUnicorn",
  "PandaRescue",
  "PetRun",
  "PetsMatch",
  "PianoKeys",
  "PipePuzzle",
  "PlantBeatZombies",
  "SaveThePets",
  "ShootSmash",
  "ShootingCubes",
  "SkyRunning3D",
  "SoccerHero",
  "SolitaireClassic",
  "StickmanVsZombies",
  "SuperGolf",
  "SuperThrow",
  "TableTennisChampionship",
  "TowerBlast3D",
  "TowerDefenseX",
  "TrafficPassing",
  "TrafficRun",
  "Transform",
  "TrappedPirate",
  "TwistyRoad",
  "VirusWar",
  "ZombieSurvival",
  "ZooBlast",
  "ZumaMarbles",
]; //选择游戏
export const EXCLUDED_GAMES = []; //排除游戏
export const FEATURED_GAMES = ["FireTheGun", "CrazyKnife", "CrazyMoto"]; //设置推荐游戏
